services:

    #
    # Event Dispatchers
    #
    cache_flusher.event_dispatcher:
        class: Mmoreram\CacheFlushBundle\EventDispatcher\CacheFlushEventDispatcher
        arguments:
            - "@event_dispatcher"